[package]
name = "gijirec-presentation"
version.workspace = true
edition.workspace = true

[dependencies]
gijirec-application = { path = "../gijirec-application" }
gijirec-domain = { path = "../gijirec-domain" }
gijirec-infrastructure = { path = "../gijirec-infrastructure" }
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }

[target.'cfg(target_os = "linux")'.dependencies]
rfd = "0.15"

[lints]
workspace = true
